### ISSUE TITLE
Create Testimonials section

### ISSUE THREAD

**Issue by loganmccaul** [loganmccaul/your-type#14]

**Comment by abbychoff** [comment]
See #8

**Comment by abbychoff** [comment]
Jk

**Comment by abbychoff** [comment]
Testimonial section on the homepage:
![YT_Homepage_July](https://user-images.githubusercontent.com/10509130/61580828-b8699e00-aadb-11e9-9989-8ba947261b8c.jpg)

### Testimonial quotes to use:
| Quote | Attribute to | Image |
|----|---|--|
| “Your-Type letters were ideal for Oktoberfest USA. It highlighted central themes of the festival in a way that our participants could interact with!” | La Crosse Festivals., INC | [Image](https://drive.google.com/file/d/13UHuJqVJOXFmLeNpSZ0WY4AXDx305Gzv/view?usp=sharing) |
|“Your-Type letters helped us achieve our objective of spreading the word about Winona to others and keep our area at the top of visitors’ minds.” | Partnership Director at Visit Winona | [Image](https://drive.google.com/file/d/1Kwi8_hXZyBSE350cauWRZpertY2MSgdO/view?usp=sharing) |
|"Wow! Your-Type Letters created a totally unique and custom backdrop for the gala event for TCWEP 10th anniversary. The stacked six-foot-tall letters were truly a show stopper and made the event!"  | Jamie Spellerberg  | Image |
